tinycompress: add bbappend to resolve do_fetch failure
tinycompress otherwise fails with the following:

ERROR: tinycompress-1.1.6-r0 do_fetch: Bitbake Fetcher Error:
FetchError('Unable to fetch URL from any source.',
'git://git.alsa-project.org/tinycompress.git;protocol=git;branch=master')

so switching to github fixes the issue.

Signed-off-by: Chris Dimich <chris.dimich@boundarydevices.com>