networkmanager: move to dynamic-layers 'networking-layer'
Fixes:

ERROR: No recipes available for:
  <...>/sources/meta-boundary/recipes-connectivity/networkmanager/networkmanager_%.bbappend

Signed-off-by: Pierre-Jean Texier <pjtexier@koncepto.io>